"""post table schema

Revision ID: cec6b3ed59e8
Revises: c9002a4d090d
Create Date: 2026-01-27 16:04:51.051294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec6b3ed59e8'
down_revision: Union[str, Sequence[str], None] = 'c9002a4d090d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding_vector'], unique=False, postgresql_ops={'embedding_vector': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
